language: node_js
node_js:
  - "10.0.0"
env:
  global:
    - SCOPE=headwood
  matrix:
    - PACKAGE=ts-build-template
    - PACKAGE=test-helper
install:
  - "cd packages/$PACKAGE; npm i"
script:
  - "cd packages/$PACKAGE; npm start cover.travis"
