language: node_js
env:
  global:
    - MOCHA_COLORS=true
cache:
  directories:
    - node_modules
    - packages/private-map/node_modules
    - packages/test-helper/node_modules
    - packages/ts-build-template/node_modules
before_install:
  - npm install npm@latest -g
install:
  - npm ci
  - npm start bootstrap
script:
  - npm start run start cover
