language: node_js
node_js:
  - "10.0.0"
env:
  global:
    - SCOPE=headwood
  matrix:
    - PACKAGE=ts-build-template
install:
  - "npx lerna bootstrap --scope=@$SCOPE/$PACKAGE"
script:
  - "npx lerna run start cover.travis --scope=@$SCOPE/$PACKAGE"
