language: node_js
env:
  global:
    - MOCHA_COLORS=true
    - SCOPE=headwood
  matrix:
    - PACKAGE=private-map
    - PACKAGE=ts-build-template
    - PACKAGE=test-helper
cache:
  directories:
    - node_modules
    - packages/private-map/node_modules
    - packages/test-helper/node_modules
    - packages/ts-build-template/node_modules
before_install:
  - npm install npm@latest -g
install:
  - cd $TRAVIS_BUILD_DIR/packages/$PACKAGE; npm ci
script:
  - cd $TRAVIS_BUILD_DIR/packages/$PACKAGE; npm start cover
