language: node_js
env:
  global:
    - MOCHA_COLORS=true
cache:
  directories:
    - node_modules
    - packages/private-map/node_modules
    - packages/test-helper/node_modules
    - packages/ts-build-template/node_modules
before_install:
  - npm install npm@latest -g
install:
  - npm ci
  - npm start bootstrap
before_script:
  - ls -Rl ${TRAVIS_BUILD_DIR}/packages/private-map/node_modules/@headwood/test-helper
  - npm start run start build -- --scope=@headwood/private-map
  - cat ${TRAVIS_BUILD_DIR}/packages/private-map/tsconfig.json
script:
  - npm start run start cover -- --scope=@headwood/private-map
