language: node_js
env:
  global:
    - MOCHA_COLORS=true
    - SCOPE=headwood
  matrix:
#    - MODULE=ts-build-template
    - MODULE=test-helper
#    - MODULE=private-map
before_install:
  - npm install npm@latest -g
  - cd $TRAVIS_BUILD_DIR/packages/$MODULE
install:
  - npm install
script:
  - npm start cover
