language: node_js
env:
  global:
    - MOCHA_COLORS=true
    - SCOPE=headwood
  matrix:
    - PACKAGE=ts-build-template
    - PACKAGE=test-helper
    - PACKAGE=private-map
before_install:
  - npm install npm@latest -g
  - cd $TRAVIS_BUILD_DIR/packages/$PACKAGE
install:
  - npm ci
script:
  - npm start cover
